In [9]:
import numpy as np 
import pandas as pd 
import seaborn as sns
from AdaBoostRegressor import CustomAdaBoostRegressor
from sklearn.datasets import load_diabetes
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import AdaBoostRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, root_mean_squared_error
import warnings 

warnings.filterwarnings('ignore')

In [10]:
df = load_diabetes(as_frame=True).frame
df

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0
...,...,...,...,...,...,...,...,...,...,...,...
437,0.041708,0.050680,0.019662,0.059744,-0.005697,-0.002566,-0.028674,-0.002592,0.031193,0.007207,178.0
438,-0.005515,0.050680,-0.015906,-0.067642,0.049341,0.079165,-0.028674,0.034309,-0.018114,0.044485,104.0
439,0.041708,0.050680,-0.015906,0.017293,-0.037344,-0.013840,-0.024993,-0.011080,-0.046883,0.015491,132.0
440,-0.045472,-0.044642,0.039062,0.001215,0.016318,0.015283,-0.028674,0.026560,0.044529,-0.025930,220.0
441,-0.045472,-0.044642,-0.073030,-0.081413,0.083740,0.027809,0.173816,-0.039493,-0.004222,0.003064,57.0

In [11]:
X, y = load_diabetes(return_X_y=True)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [13]:
scalar = StandardScaler()

X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

## Custom Model

In [14]:
model = CustomAdaBoostRegressor(base_estimator = LinearRegression(),
        n_estimators=50,
        learning_rate=0.1)

In [15]:
model.fit(X_train, y_train)

In [16]:
custom_pred = model.predict(X_test)
custom_pred

array([147.65806848, 177.45877125, 143.59545776, 277.48610271,
       130.49344043, 101.85994957, 261.43187144, 192.22846196,
        95.69725282, 119.37627403,  98.93751602, 158.43453159,
        54.16415476, 209.69039395, 107.68874743, 134.30915832,
       224.2295858 , 250.33953238, 191.53471118, 218.50503551,
       202.86939222,  92.94257033,  72.7631497 , 192.66200132,
       156.25802292, 162.66613885, 189.34728546, 176.47581695,
        50.32431271, 120.327044  , 178.021677  ,  88.18829449,
       142.17050099, 185.33898346, 178.0778782 , 197.55868933,
       131.79924866, 128.94094594, 155.78277758,  60.63852616,
        75.52534857, 112.85777923, 162.52784684, 157.98798166,
       167.5118263 ,  64.11122482,  75.60915029, 111.11236282,
        52.29272562, 162.86039271, 151.56481876,  65.46641268,
       106.80532269, 110.49293782, 175.24779576, 152.32349459,
        99.10799946, 209.52571136, 121.05433418,  77.74617891,
       188.56079327, 201.36234384, 144.41611481, 112.16952678,
       129.30244485, 199.01806395, 173.27265672, 164.96335017,
       120.18352521, 147.6489111 , 179.9177276 , 200.7963818 ,
       229.19946437, 146.49681228,  80.10747923, 156.467125  ,
       201.22768339, 204.45328773, 164.40079611, 196.17315795,
       110.67650285, 136.52210557,  59.77559621,  61.43253877,
       115.76790335,  82.75860546,  77.22773431,  54.13040113,
       161.63328991])

In [17]:
custom_r2 = r2_score(y_test, custom_pred)
custom_rmse = root_mean_squared_error(y_test, custom_pred)
print(custom_r2)
print(custom_rmse)

0.4637623853673025
53.30167216501371

## Sklearn Model

In [18]:
sk_model = AdaBoostRegressor(
    estimator=LinearRegression(),
    n_estimators=50,
    learning_rate=0.1
)

sk_model.fit(X_train,y_train)

AdaBoostRegressor(estimator=LinearRegression(), learning_rate=0.1)

In [19]:
sk_pred = sk_model.predict(X_test)
sk_pred

array([144.31195029, 176.53019606, 141.1248326 , 278.13534076,
       128.3438677 ,  97.66090638, 257.65833624, 188.5091223 ,
        94.44515419, 116.42119303,  95.36246792, 161.98154874,
        53.41586671, 211.41826328, 105.28730212, 132.77817435,
       222.92336198, 251.89615954, 189.72891525, 218.41921557,
       202.06122497,  92.669495  ,  69.3022103 , 191.76954273,
       153.41928101, 164.00201553, 189.09306914, 178.14948932,
        49.3179083 , 117.09417221, 177.45310219,  86.34160468,
       141.59652229, 185.68161043, 177.61387079, 193.10568615,
       130.08861282, 126.39263954, 155.59132052,  59.89051899,
        72.54712897, 109.24022997, 162.41240292, 160.31712051,
       169.27547797,  63.69206873,  74.76016228, 111.16414525,
        51.10556728, 163.74779341, 152.32062322,  62.62045118,
       106.82614348, 109.9307925 , 174.40720041, 151.91896043,
        98.18583474, 209.55937357, 119.71109786,  80.25142509,
       187.49776089, 202.39522971, 141.16665021, 108.16000962,
       128.11347046, 199.79523558, 173.47923608, 163.90796339,
       121.98068365, 146.37450641, 179.67526852, 199.37635159,
       229.40980839, 146.92633969,  80.87958088, 155.42176424,
       196.60586914, 205.7055263 , 163.72718423, 196.20545165,
       109.35589027, 137.1685604 ,  57.30389103,  58.05602259,
       114.44811026,  82.25117503,  78.20180791,  54.9377115 ,
       161.91964892])

In [20]:
sk_r2 = r2_score(y_test, sk_pred)
sk_rmse = root_mean_squared_error(y_test, sk_pred)
print(sk_r2)
print(sk_rmse)

0.45945682787272235
53.51522916474194

## Comparison

In [22]:
comparison_df = pd.DataFrame(
    {
        "CustomModel" : [custom_rmse, custom_r2],
        "SKModel" : [sk_rmse, sk_r2]
    },
    index = ['rmse', 'r2']
)

comparison_df

      CustomModel    SKModel
rmse    53.301672  53.515229
r2       0.463762   0.459457

## Conclusion

The Custom AdaBoost Regressor achieved performance close to Scikit-learn's AdaBoost Regressor.

- **Custom AdaBoost Regressor RMSE:** 53.301672
- **Scikit-learn AdaBoost Regressor RMSE:** 53.515229
- **Custom AdaBoost Regressor R²:** 0.463762
- **Scikit-learn AdaBoost Regressor R²:** 0.459457

The custom model achieved a slightly lower RMSE and a slightly higher R² score than the Scikit-learn model on the test dataset. These results indicate that the custom implementation successfully captures the core AdaBoost regression mechanism and produces comparable predictive performance.

However, small differences may occur due to differences in implementation details, base estimator configuration, and training behavior.

**AdaBoost Regressor → DONE ✅**